### ISSUE TITLE
composer.json creates empty autoload namespace

### ISSUE THREAD

**Issue by redemption** [jmhobbs/Swiftmailer-Transport--AWS-SES#19]
Hi there,

The composer.json file has an autoload entry that creates an empty namespace which Symfony's autoloader (and possibly others) don't like.

Is it perhaps better to leave out the autoload portion of the composer file altogether?

**Comment by jmhobbs** [comment]
This is a pretty old issue, is it still a problem?

**Comment by jmhobbs** [comment]
Closing as this is very old and I can't confirm it's still a problem.  Please re-open if it is.

Thanks!

**Comment by redemption** [comment]
The autoload entry still exists as far as I can see.

This is what I have inside _/vendor/composer/autoload_namspaces.php_:

`'' => array($vendorDir . '/jmhobbs/swiftmailer-transport-aws-ses/classes'),`

However, I can't confirm whether this still breaks Symfony as we don't seem to have any problems anymore, so unless someone else can report that I think it's safe to close
