### ISSUE TITLE
Persistent HTTP Connections

### ISSUE THREAD

**Issue by mllrmat** [jmhobbs/Swiftmailer-Transport--AWS-SES#25]
Would it be possible to implement persistent HTTP connections? I am using your transport module to send large quantities of emails and as far as I see it the HTTP connection is opened and closed for each email. 
Thank you
Mathias

**Comment by jmhobbs** [comment]
I did some poking around, and I think this is doable, for sure.  I'll start a branch for it.

**Comment by muellm** [comment]
Great! Thank you so much!

I looked a bit at the code and thought if it would be possible to make use of pfsockopen(), making the connection static and taking out the fclose() in the read() method? It would of course need some error handling in case no open connection exists. This might be a bit tricky...

A important question might be how to avoid having too many connections open, because a connection might not be closed properly?

**Comment by jmhobbs** [comment]
I'm not sure `pfsockopen` is necessary, I like having the socket lifecycle tied to the transport object.

We should be able to just leave the socket open and use `Connection: keep-alive`.

I've got this working without chunked encoding, but there's some finicky state or something I'm missing with chunked transfer I'm looking into.

**Comment by jmhobbs** [comment]
Found it!

The current code counts on the remote server to drop the connection, which is why we send the `Connection: close` header.

With `keep-alive` I can't just watch for `feof`on the socket, we actually have to parse some HTTP.

Maybe I'll look into that persistent socket after all :)

**Comment by jmhobbs** [comment]
Nope!  Wasn't thinking straight.  Still have to parse some HTTP headers to make this work, otherwise the server closes the persistent socket as well.

I'll work on a patch tonight.

**Comment by jmhobbs** [comment]
@muellm branch is open.  It works, but I'm not sure I'm ready to merge it yet.

Please feel free to test it though, it's working here.

**Comment by muellm** [comment]
Thank you sooo much for your fast solution. I will test this during the next days and give you feedback as soon as I have some results.

**Comment by jmhobbs** [comment]
@muellm Any luck in production?  Had any problems?  Sending going any faster?

**Comment by muellm** [comment]
Hi, 
sorry for the late reply, I have the code in production both with/out persistent connection enabled. It works well, but the bottleneck is in my application at the moment and the speed increase of the persistent connection is only to a small degree, but I attribute this to my applications. Once I have tuned it further I will feedback.

But thank you so much for your help!

Mathias

**Comment by ovr** [comment]
Any news?

**Comment by jmhobbs** [comment]
I've merged this up for Swiftmailer 5.x, and I'm about to merge for 6.x as well.
