### ISSUE TITLE
Call to a member function getMessage() on string

### ISSUE THREAD

**Issue by iadj** [jmhobbs/Swiftmailer-Transport--AWS-SES#27]
I configured this plugin for use with `yii2-swiftmailer` on my Yii2 installation as follows:
Installing & configuring `Swift_Events_ResponseReceivedListener`:
```
      'mailer' => [
           'class' => 'yii\swiftmailer\Mailer',
           'viewPath' => '@frontend/mail',
           'htmlLayout' => '@frontend/mail/layouts/html',
           'transport' => [
               'class' => 'Swift_SmtpTransport',
               ...
               'plugins' => [
                   [
                       'class' => 'Swift_Events_ResponseReceivedListener',
                       'constructArgs'=>
                       [
                         'callback' => function ($message, $body) {
                                         echo sprintf($body->SendRawEmailResult->MessageId);
                                       }
                        ]
                   ],
               ],
             ],
           ],
```
### What's expected?
The mailer object should return the Message ID provided by the ResponseReceivedListener plugin after the message has been sent.
This is my emailing code:
```
$mailer->compose('content', ['content' => $letter->content])
          ->setTo($user->email)
          ->setSubject($letter->title);
          ->send();
```

### What do you get instead?
Upon sending the mail I receive the following error:
```
PHP Fatal Error 'yii\base\ErrorException' with message 'Call to a member function getMessage() on string'
in \vendor\jmhobbs\swiftmailer-transport-aws-ses\classes\Swift\Events\ResponseReceivedListener.php:16
```
Turns out the `$event->getResponse()` function in ResponseReceivedListener.php returns response code strings, and no object. i.e:

```
220 email-smtp.amazonaws.com ESMTP SimpleEmailService-1383awdawd763 7anawddwadwSpawddwa
250-email-smtp.amazonaws.com
250-8BITMIME
250-SIZE 10485760
250-STARTTLS
250-AUTH PLAIN LOGIN
250 Ok
220 Ready to start TLS
250-email-smtp.amazonaws.com
250-8BITMIME
250-SIZE 10485760
250-STARTTLS
250-AUTH PLAIN LOGIN
250 Ok
334 AWDDAadwaU6
334 UAWDWDADmQ6
235 Authentication successful.
250 Ok
250 Ok
354 End data with <CR><LF>.<CR><LF>
250 Ok 01adwadwawd66e8d27-8acawdawddawf1b-4d8bdawadwdawc16f59a0-000000
```

I'm not certain if this issue lies with yii2-swiftmailer or the plugin being outdated (or perhaps it's me doing it incorrectly).

**Comment by iadj** [comment]
The issue is because yii2-swiftmailer uses the `Swift_SmtpTransport` class instead of `Swift_AwsTransport`. I read that Amazon suggests using SmtpTransport over AwsTransport. Is there a way to use this plugin with `Swift_SmtpTransport`?

**Comment by jmhobbs** [comment]
Hello!  I'm not very familiar with Yii2, but to me it looks like you might just need to change your config a bit in the `transport` section.

```diff
    'transport' => [
-       'class' => 'Swift_SmtpTransport',
+       'class' => 'Swift_AWSTransport',
        ...
        'plugins' => [
```

`Swift_AWSTransport` and `Swift_SMTPTransport` are mutually exclusive, they provide the same function and can not be used together.   That said, AWS does support SMTP sending, so you could use that if you wish.

**Comment by iadj** [comment]
Hey @jmhobbs, that indeed appeared to be the issue! I did read that SMTP is recommended over AWSTransport. Are there major differences or is it still safe and up to date to use AWSTransport?

**Comment by jmhobbs** [comment]
SMTP is rock solid code, it's used all over and has had it's bugs worked out, where as AWS is a lot less used.  This project exists because SES didn't launch with SMTP support, they added that later.

For bulk throughput you might get better performance out of the AWS transport, especially with the [persistent connections branch](https://github.com/jmhobbs/Swiftmailer-Transport--AWS-SES/tree/feature/persistent-connections), but for one-off sends and transactional mail, SMTP is probably the safer option.

Both work though :)

**Comment by jmhobbs** [comment]
Closing as resolved.
