### ISSUE TITLE
how to configure on newer Symfony/Swiftmailer versions?

### ISSUE THREAD

**Issue by drzraf** [jmhobbs/Swiftmailer-Transport--AWS-SES#38]
Looking at [configuration definition for swiftmailer](https://github.com/symfony/swiftmailer-bundle/blob/master/DependencyInjection/Configuration.php) I wonder how to setup AwsSes transport bridge in newer Symfony versions.
Couldn't find a corresponding updated documentation.

**Comment by garak** [comment]
I agree on this. Readme is showing instructions for Symfony 1 (that could be maybe useful, but it's a bit odd, since that version is unsupported since a loooong time)
No instructions for current Symfony versions (3 and 4) 😔

**Comment by garak** [comment]
I managed to solve. I found that on latest Symfony you just don't need this library, you can use the [configuration you can found on official docs](https://symfony.com/doc/current/email.html#using-cloud-services-to-send-emails):

>MAILER_URL=smtp://email-smtp.us-east-1.amazonaws.com:587?encryption=tls&username=YOUR_SES_USERNAME&password=YOUR_SES_PASSWORD

**Comment by jmhobbs** [comment]
Thanks for following up.  I do recommend folks use the built in SMTP stuff since AWS released it.  I'll try to make that more clear in the README.

**Comment by drzraf** [comment]
Features-wise, SMTP is not on par with native API, especially with regards of:
- logging / monitoring
- user access & API permission

**Comment by jmhobbs** [comment]
I'm happy to re-open this one, but I have zero knowledge of Symfony, so I won't be able to work this one.
