### ISSUE TITLE
SES Signature Version 3 EOL October 2020, Version 4 required

### ISSUE THREAD

**Issue by gregesposito** [jmhobbs/Swiftmailer-Transport--AWS-SES#41]
Is it possible to update the software to be V4 compatible for a drop-in update?

Received this email, looks like Signature Version 3 is being end-of-lifed in October:

Amazon Web Services currently supports Amazon Simple Email Service (Amazon SES) API requests that are signed using either Signature Version 3 or Signature Version 4 processes. Signature Version 4 offers enhanced security for authentication and authorization of Amazon SES customers by using a signing key instead of your secret access key.

To enhance the security of Amazon SES customers, beginning October 1, 2020, support for Signature Version 3 will be turned off (deprecated) in Amazon SES, and only Signature Version 4 will be supported going forward. Amazon SES customers who are currently using Signature Version 3 must migrate to Signature Version 4 by September 30, 2020. After that, Amazon SES will only accept requests that are signed using Signature Version 4. For more information, see the Signature Version 4 signing process [1] in the AWS General Reference.

You can easily identify API requests that use Signature Version 3 by looking at the request headers. Requests that use the Signature Version 3 resemble the following example:

X-Amzn-Authorization: AWS3-HTTPS AWSAccessKeyId=AKIAIOSFODNN7EXAMPLE,Algorithm=HMACSHA256,Signature=lBP67vCvGl...

What happens if I don't make updates?

Requests signed with Signature Version 3 that are made after September 30, 2020 will fail to authenticate with Amazon SES. Requesters will receive an InvalidClientTokenId sender error, stating the security token included in the request is invalid. For more information, see Authenticating requests to the Amazon SES API [2] in the Amazon SES Developer Guide.

References:
[1] https://docs.aws.amazon.com/general/latest/gr/signature-version-4.html
[2] https://docs.aws.amazon.com/ses/latest/DeveloperGuide/using-ses-api-authentication.html

**Comment by jmhobbs** [comment]
I'll take a look, I got this email too and meant to round back to it.

**Comment by Alexander-Pop** [comment]
@jmhobbs do you have progress on this? TY

**Comment by lucasrothamel** [comment]
@jmhobbs also dropping a line here - is there any chance for this to be implemented soon, or do I need to re-implement our email sending in the next few weeks?

**Comment by jmhobbs** [comment]
Hey all 👋 

I'll take another stab at this tonight, but you may consider moving to the SMTP interface of SES unless you have a weird edge case where this library works better for you.

Thanks for your patience!

**Comment by lucasrothamel** [comment]
@jmhobbs on our side we're switching to SMTP auth

**Comment by gregesposito** [comment]
We too switched to SMTP. Here's our one liner that we implemented across our codebase, just add in the defined variables yourself like tls and the user/pass:

grep -rli '$transport = Swift_AWSTransport::newInstance(AWSAccessKeyId, AWSSecretKey);' * | xargs -i@ sed -i 's/$transport = Swift_AWSTransport::newInstance(AWSAccessKeyId, AWSSecretKey);/$transport = Swift_SmtpTransport::newInstance(AWSServerSMTP, 25, AWSEncryptionSMTP)->setUsername(AWSAccessKeyIdSMTP)->setPassword(AWSSecretKeySMTP);/g' @

Before:
$transport = Swift_AWSTransport::newInstance(AWSAccessKeyId, AWSSecretKey);

After:
$transport = Swift_SmtpTransport::newInstance(AWSServerSMTP, 25, AWSEncryptionSMTP)->setUsername(AWSAccessKeyIdSMTP)->setPassword(AWSSecretKeySMTP);

I'm happy with this. @jmhobbs I was so glad to have found your code years ago, it helped me get my foothold in AWS and actual useful PHP.

**Comment by SushmaGnt** [comment]
Hi, i am new to this, tried adding this code,
$transport = Swift_SmtpTransport::newInstance(AWSServerSMTP, 25, AWSEncryptionSMTP)->setUsername(AWSAccessKeyIdSMTP)->setPassword(AWSSecretKeySMTP); is not working for me!

getting below error:
"A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond"

Is there any configurations to be updated/configured ? Can anyone help me on this. currently we are using swiftmailer..


Thanks in advance

**Comment by gregesposito** [comment]
Sorry, when I noted the variables needed to be changed I didn't show an example. This again is based off the simplest of setups, your experience may vary. 

You need to get AWS SES SMTP creds from https://docs.aws.amazon.com/ses/latest/DeveloperGuide/smtp-credentials.html

Assuming you use the following defines from the example at https://github.com/jmhobbs/Swiftmailer-Transport--AWS-SES/blob/master/example/config.php.example 

define('AWSAccessKeyId', 'OLD-SES-ACCESSKEY');
define('AWSSecretKey', 'OLD-SES-SECRETKEY');

These new defines can be setup as well, so you can have both during your transition

define('AWSAccessKeyIdSMTP', 'NEW-SES-SMTP-ACCESSKEY');
define('AWSSecretKeySMTP', 'NEW-SES-SMTP-SECRETKEY');
define('AWSServerSMTP', 'email-smtp.us-east-1.amazonaws.com');
define('AWSEncryptionSMTP', 'tls');

Hope that helps.

**Comment by SushmaGnt** [comment]
Still same error!
Does swift mailer version matters?Currently we are using swift4.1.3

Thanks In advance

**Comment by Alexander-Pop** [comment]
//swiftmailer 6.0    
    $hostname = 'email-smtp.us-west-2.amazonaws.com'; // or email-smtp.us-east-1.amazonaws.com
    $port     = 25;
    $security = 'tls';
    $username = 'YYYYYSOMENAMEYYYYY';
    $password = 'yourpassword';
    $fromEmail - foo@foo.com

    $transport = (new Swift_SmtpTransport($hostname, $port, $security))
        ->setUsername($username)
        ->setPassword($password);

    $mailer = new Swift_Mailer($transport);

    // Composite the message
    //$message = Swift_Message::newInstance()
    $message = (new Swift_Message())
        ->setSubject($msgTitle)
        ->setFrom([$fromEmail => 'YOUR TEXT'])
        ->setTo([$recipientAddress]);

/* next has to be same as for SES */

**Comment by lucasrothamel** [comment]
I am having a huge issue with above SMTP transport, which we didnt have when using the SES API. 
We're running a long running mailer process. AWS SMTP drops any connection after 30 seconds - and Swift SMTP Transport doesnt reconnect. It just gets stuck on "451 no data" from AWS, and never reconnects - doesnt matter how often one tells it to "stop, start", "reset", etc.
Any ideas?

**Comment by SushmaGnt** [comment]
Hi, Still i have same issue

**Comment by Alexander-Pop** [comment]
do you use latest swiftmailer?
try logging
$logger = new Swift_Plugins_Loggers_ArrayLogger();
$mailer->registerPlugin(new Swift_Plugins_LoggerPlugin($logger));
and try after
$result = $mailer->send($message);
try
print_r($logger); 
or 
echo $logger->dump();
//var_dump($result);
make sure you use proper $hostname in my code above.

**Comment by jmhobbs** [comment]
I've got a PR up that is a drop in for the v4 signing.  It's a little shoehorned in there, but it is working in my testing.

If anyone can give that a spin, I'd appreciate it, otherwise I'll push that out in a few days.

I will be marking this repo and this package deprecated after I can add some good SMTP instructions to the README.

PR's _most_ welcome!

**Comment by lucasrothamel** [comment]
Thanks @jmhobbs for your efforts. We did get the SMTP working in the meantime, it was a bug in some wrapper code written in 2017, based on assumptions of an old swiftmailer version.

So we're just using the Swift_SmtpTransport transport with host, username, password, port=587 and encryption=tls. Quite straight forward.

**Comment by jmhobbs** [comment]
Excellent. Yes, the SMTP transport is definitely the better option, glad it’s working for you.
