### ISSUE TITLE
SES Signature Version 3 EOL October 2020, to be upgraded to version4

### ISSUE THREAD

**Issue by SushmaGnt** [jmhobbs/Swiftmailer-Transport--AWS-SES#42]
Currently signature SES signature to be upgraded to version4. What all the steps to be followed? Can anyone help  on what all changes to be made?

Currently we are using swiftmailer 

Thanks in advance

**Comment by jmhobbs** [comment]
Hello!  Please follow issue #41 for discussion.  The current option is to switch to the SMTP interface with SES to prevent any problems.  Still trying to get a v4 signer implemented, but SMTP is the better long term option.  Thanks!
